### ISSUE TITLE
Saving problems 

### ISSUE THREAD

**Issue by FabianaGiannuzzi** [DataAccess2020/Capstone-Project---FRS#4]
Ciao @DeAngelisA , 
stiamo riscontrando dei problemi nel salvataggio del dataset creato. Abbiamo provato a salvarlo in formato csv usando il comando "write.table" (e altri) ma ci è impossibile, pare per via del fatto che nel creare il vettore per il testo degli articoli abbiamo impostato "mode = list". Infatti, quando mandiamo il comando write.table ci esce il seguente errore: 
_### _Error in write.table(datlinks1, "DATASET.csv", sep = ";", row.names = FALSE,  : 
  tipo 'list' non implementato in 'EncodeEleme_nt'_

Vorremmo capire se c'è un altro modo di salvare il dataset o, meglio ancora, se c'è un modo per salvare gli articoli in un **mode** che _non_ sia **list**. 

Abbiamo a lungo cercato su internet senza trovare una soluzione.

Grazie in anticipo!

**Comment by DeAngelisA** [comment]
@FabianaGiannuzzi : convertite da lista a character vector prima di salvare. Non so, mettiamo che la lista è `datlinks1`, allora provate una cosa tipo: `as.character(unlist(datlinks1))`. Fatemi sapere!

**Comment by sofiaragazzi** [comment]
Ciao @DeAngelisA ! Abbiamo provato il codice che hai scritto, ma l'output diventa di dimensioni diverse rispetto al numero totale degli articoli. Secondo me perché con unlist, R separa ogni "paragrafo" selezionato dal css. Da questo risultato non sono in grado di ricostruire una tibble ordinata, proprio perché "links" e "testo" sono di due lunghezze diverse.
