### ISSUE TITLE
Updated readme

### ISSUE THREAD

**Issue by FabianaGiannuzzi** [DataAccess2020/Capstone-Project---FRS#5]
@sofiaragazzi @Riccardo-Ruta 
Ho aggiornato e completato il *readme*. Dategli un occhiata e ditemi cosa ne pensate. 

Ho creato un paragrafo relativo alla struttura della nostra repository. Probabilmente la struttura che ho definito (folders presenti nei brench ecc) non corrisponde a come in nostri singoli brench sono strutturati ma potremmo usarla come riferimento in modo tale da dare al progetto una struttura standard e quindi chiara. 

Aggiorniamoci qui se facciamo delle modifiche alla parte della struttura così che tutti siamo sempre aggiornati sull'ultima "versione".

**Comment by sofiaragazzi** [comment]
Va bene! Ho visto le modifiche, molto meglio così. Ho fatto un paio di piccole correzioni, ma mi piace. 
Forse io aggiungerei il folder con i dizionari per fare la sentiment analysis ( 🤞 ).
